### ISSUE TITLE
"atlas" CLI reports "You are not authorized for this resource" when "mongocli atlas" does not

### ISSUE THREAD

**Issue by SteveH-US** [mongodb/mongodb-atlas-cli#1133]
**Describe the bug**
A clear and concise description of the bug.

As requested, I followed the [migration steps for using "atlas" rather than "mongocli atlas"](https://www.mongodb.com/docs/atlas/cli/stable/migrate-to-atlas-cli/). However, I'm not getting the "You are not authorized for this resource" errors for the same configuration, but running the same comment through "mongocli atlas" works. I have "organizational" owner" rights. 

**To Reproduce**
Using `mongocli`
```shell
$ mongocli iam projects list | grep "\"id\":" | wc -l
      11
```
Using `atlas`
```shell
$ atlas projects list
Error: GET https://cloud.mongodb.com/api/atlas/v1.0/groups?itemsPerPage=100&pageNum=1: 401 (request "") You are not authorized for this resource.
```

**Expected behavior**
Please explain what you expected to happen.

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Mac OS 12.3.1 M1Pro
 - MongoCLI version 1.24.1
 - Atlas cli version1.0.2
 - Ops Manager Version: N/A

**Additional context**

**Comment by gssbzn** [comment]
Hi @SteveH-US before I look into possible errors on our side can you please confirm that the config files look a like?
to open the config file for `mongocli` you can do `mongocli config edit` for atlas you can do `vi ~/Library/Application\ Support/atlascli/config.toml`

**Comment by gssbzn** [comment]
Also to confirm, was the migration relying on the automated atlas cli config file creation or was this related to an automated pipeline that required manual intervention for the file?

**Comment by SteveH-US** [comment]
@gssbzn 

Here's my config file with the keys redacted
```yaml
mongosh_path = "/Users/steveh_1/.mongodb/mongosh"
skip_update_check = true

[default]
  mongosh_path = "/opt/homebrew/bin/mongosh"
  org_id = "***"
  output = "json"
  private_api_key = "***"
  project_id = "***"
  public_api_key = "***"
  service = "cloud"

[mom_mia]
  ops_manager_url = "https://mama.mia.ulti.io/"
  organization_id = "***"
  private_api_key = "***"
  project_id = "***"
  public_api_key = "***"
  service = "ops-manager"
```

I followed the [migration instructions](https://www.mongodb.com/docs/atlas/cli/stable/migrate-to-atlas-cli/). It appears that the `atlas config init` command reused the `mongocli` config file that was there already.

**Comment by SteveH-US** [comment]
There appears to be a bug in the way the `atlas` cli handles the init. It appears to copy the `mongocli` configuration as is when running `atlas config init`. I say this because when I rename the existing file, "~/Library/Application\ Support/atlascli/config.toml" and run 'atlas config init' again, I am able to get the expected results back. So, it appears that a `mongocli` configuration it copied, the one quoted above, causes the said erroneous error.
