### ISSUE TITLE
config.toml not getting updated with new values after doing atlas config init more than once

### ISSUE THREAD

**Issue by pawan-saxena** [mongodb/mongodb-atlas-cli#1379]
I did initialize the atlas using : `atlas config init`.
I got the profile created successfully.
Then I noticed the config I did put was wrong. So I did `atlas config init` several times and found that the config.toml was not getting updated with new values.

**To Reproduce**
1. Run 'atlas config init' multiple times
2. See : 'There was an error fetching your organizations: You are not authorized for this resource.'

**Expected behavior**
The  corresponding output should come on console for the atlas commands being run after it is being initialised with correct config multiple times

**Desktop 
- MacOS Monetery (v12.3.1)
 - atlas CLI  (v 1.1.4)

**Comment by blva** [comment]
Hi!

Thanks for reporting this issue.

Potential fixes:
- You can edit the specific wrong configuration as opposed to run init. For example, if the org id is wrong, you can try `atlas config edit set org_id <new_id_value>` - [docs](https://www.mongodb.com/docs/atlas/cli/stable/command/atlas-config-set/).
- Run `atlas config edit` and see the `config.toml` file. All the values should be in `[default]`profile. You should be able to erase all the values there to try running config init again.

Reproducing the issue:
To help me reproducing this issue, could you please provide the following:
- What is your authentication method? Did you run atlas login or did you set API keys through ``atlas config init`?
- What are the values in the config that are wrong?
- What is the path of `config.toml` file that you're referring to? Is it possible you have mongocli also installed?
