### ISSUE TITLE
`atlas kubernetes generate` does not catch gcp peerings in AtlasProject

### ISSUE THREAD

**Issue by zelig81** [mongodb/mongodb-atlas-cli#1657]
**Describe the bug**
A clear and concise description of the bug.
- `atlas kubernetes generate` does not catch gcp peerings in AtlasProject while catching aws peerings

**To Reproduce**
0. have Atlas project with aws and gcp peerings
1. Run 'atlas kubernetes generate'
2. get in k8s manifest of AtlasProject only aws peerings

**Expected behavior**
Please explain what you expected to happen.
- I expected to get aws and gcp peerings in `networkPeerings` of AtlasProject

**Desktop (please complete the following information):**
 - OS: osx
 - MongoCLI version: 1.4.0

**Additional context**

**Comment by igor-karpukhin** [comment]
Hi @zelig81. This was fixed with https://github.com/mongodb/mongodb-atlas-cli/pull/1596/ and will be published with the next release of the Atlas CLI

**Comment by zelig81** [comment]
> @zelig81 I'd love to chat about your experiences using the operator - if you're interested please reach out to me at dan.mckean@mongodb.com

Will be glad to talk with you, most chances it will happen on Monday

**Comment by zelig81** [comment]
> Hi @zelig81. This was fixed with https://github.com/mongodb/mongodb-atlas-cli/pull/1596/ and will be published with the next release of the Atlas CLI

Thank you! Could it be that you can share with me some estimation when it is going to be released?

**Comment by igor-karpukhin** [comment]
@zelig81, the release is planned for the next week. I'll let you know when it is released.

**Comment by igor-karpukhin** [comment]
Fixed with the atlas-cli v1.5.0
