### ISSUE TITLE
1.29.0 release did not get completed

### ISSUE THREAD

**Issue by chenrui333** [mongodb/mongodb-atlas-cli#1772]
👋 looks like 1.29.0 release did not get completed (the release did not marked as latest release). Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/125854

**Comment by fmenezes** [comment]
Hi there, I'm on the mongocli/atlascli team on MongoDB, I acknowledge the problem and we've already identified the issue, we will look at fixing this on Monday.

Thanks for flagging.

**Comment by chenrui333** [comment]
Thanks for confirming it @fmenezes!

**Comment by fmenezes** [comment]
FYI we are re-releasing mongocli v1.29.0

**Comment by chenrui333** [comment]
Looks like same thing happens for 1.7.4 again, https://github.com/Homebrew/homebrew-core/pull/133873 cc @fmenezes

**Comment by chenrui333** [comment]
Thanks!
