### ISSUE TITLE
alert settings list throws "unexpected end of JSON input"

### ISSUE THREAD

**Issue by sven-hergenhahn-dmtech** [mongodb/mongodb-atlas-cli#2029]
**Describe the bug**

JSON output of `atlas alerts settings list` fails (often) with 
`Error: json: error calling MarshalJSON for type *admin.ServerlessMetricThreshold: unexpected end of JSON input`

e.g. running it with `--limit 3` works, with `--limit 3 --page 2` fails, page 3 as well, page 4 works again

Of course, getting all configs with --limit 500 then fails as well.

**To Reproduce**
1. Run 'atlas alerts settings list --limit 3 --page 2'
2. See error

**Expected behavior**
Getting correct JSON for each "page"

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4 (M1 Pro)
 - MongoCLI version atlascli version: 1.8.0
git version: homebrew-release
Go version: go1.20.5
   os: darwin
   arch: arm64
   compiler: gc

 - Ops Manager Version: ?

**Comment by wtrocki** [comment]
Hi would it be possible to run command with --debug?

**Comment by wtrocki** [comment]
We going to address the issue. For the moment please use --debug as workaround

**Comment by wtrocki** [comment]
Sincere apologies for that regression. Fix have been released in https://github.com/mongodb/mongodb-atlas-cli/releases/tag/atlascli%2Fv1.9.0
