### ISSUE TITLE
atlas networking containers list throws error

### ISSUE THREAD

**Issue by laurencee** [mongodb/mongodb-atlas-cli#2073]
**Describe the bug**
Attempted to execute `atlas networking containers list` after auth login.

I get the following error back
`Error: template: output:2:31: executing "output" at <.RegionName>: can't evaluate field RegionName in type interface {}`

**Desktop (please complete the following information):**
`atlas --version` output
```
atlascli version: 1.9.1
git version: 730ed8bebeaa69592c31ef47539795ac4a18291f
Go version: go1.19.10
   os: windows
   arch: amd64
   compiler: gc
```

**Additional context**
First time trying the atlas cli, I just wanted to find out what network containers existed.

In my case, there were no containers when I queried the http api myself without specifying a provider.

**Comment by wtrocki** [comment]
Thank you for reporting issue. We are working for the fix. 
As workaround we recomend to use `-o JSON` to get output of the command in JSON format

**Comment by wtrocki** [comment]
We have made a fix for the issue. It will be included in the next release of the atlas CLI.

**Comment by wtrocki** [comment]
The issue has been fixed in the latest release.
