### ISSUE TITLE
500 error when getting events

### ISSUE THREAD

**Issue by LuisCordobaDataSite** [mongodb/mongodb-atlas-cli#2691]
**Describe the bug**
I am running the command 
`$atlas events projects list --output json --projectId <projectId> --maxDate 2024-03-01T15:21:10+00:00Z --minDate 2024-03-01T15:01:10+00:00Z --limit 500 --page 435`
And getting the following error:
ERR Error: https://cloud.mongodb.com/api/atlas/v2/groups/<projectId>/events GET: HTTP 500 Internal Server Error ( Error code: "TIMEOUT _WHILE_PAGING") Detail: Unable to calculate the total number of results. Retry with includeCount=false. Reason: Internal Server Error. Params: []
I would gladly use the includeCount=false but checking the documentation, I don't have that option in the command

**To Reproduce**
If I run only the command above, it works just fine, the problem is I'm running it in a loop, there are 435+ pages, so I think is overloading the server, if using includeCount=false actually fixes, I'm fine but I need that option in the CLI.

**Expected behavior**
Not throwing an error and getting the expected output

**Screenshots**
If possible, add screenshots to help explain your problem.
![Screenshot 2024-03-01 at 11 02 16 AM copy](https://github.com/mongodb/mongodb-atlas-cli/assets/138828956/03fef7fc-82b5-4052-9506-d0fba0052a6a)

**Desktop (please complete the following information):**
 - OS:
 3.19.1
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.1
PRETTY_NAME="Alpine Linux v3.19"

 - MongoCLI version [e.g. 1.2]
 atlascli version: 1.14.2
git version: 47dc06c7a9b1183cd8b0027306dd839d8547893d
Go version: go1.21.6
   os: linux
   arch: amd64
   compiler: gc
   

**Additional context**
As mentioned before, I don't get the error just running the command isolated, I get it after running the other 400+ pages, pretty sure is overloading the server to make such an expensive call to count the total amount. Just wanted to know if there is a way to send the includeCount=false that I'm missing or in fact this is an issue

**Comment by andreaangiolillo** [comment]
Hello @LuisCordobaDataSite 👋 Thanks for opening the issue.

The fix will be available in the next AtlasCLI release scheduled for the 7th of March.  Feel free to reopen this issue if you're still hitting this error with the latest release.

Thanks!
