### ISSUE TITLE
Undefined response type

### ISSUE THREAD

**Issue by LuisCordobaDataSite** [mongodb/mongodb-atlas-cli#2866]
**Describe the bug**
When I try to execute a command:
`atlas logs download atlas-12uho2-shard-00-01.dssnf.mongodb.net mongodb-audit-log.gz --projectId 65a32c3fb244d862c601d12d --out /var/log/atlas/65a32c3fb244d862c601d12d_atlas-12uho2-shard-00-01.dssnf.mongodb.net_1712850826-1712852026-mongodb-audit-log.gz --start 1712850826 --end 1712852026`
I get an error that says: "Error: undefined response type"
The reason I think this is a bug is that I was using this same code (the only difference is the timestamps), it started failing last week according to my logs, which match with your latest release.

**To Reproduce**
1. Run: $ atlas logs download atlas-12uho2-shard-00-01.dssnf.mongodb.net mongodb-audit-log.gz --projectId 65a32c3fb244d862c601d12d --out /var/log/atlas/65a32c3fb244d862c601d12d_atlas-12uho2-shard-00-01.dssnf.mongodb.net_1712850826-1712852026-mongodb-audit-log.gz --start 1712850826 --end 1712852026
2. See error: `Error: undefined response type`

**Expected behavior**
If the command is right, I expect it to download the logs.
If the command is wrong, a more detailed explanation of the problem would be very useful to fix it myself.

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
OS:
3.19.1
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.1
PRETTY_NAME="Alpine Linux v3.19"

MongoCLI version [e.g. 1.2]
atlascli version: 1.16.0
git version: https://github.com/mongodb/mongodb-atlas-cli/commit/47dc06c7a9b1183cd8b0027306dd839d8547893d
Go version: go1.21.6
os: linux
arch: amd64
compiler: gc

**Additional context**

**Comment by tibulca** [comment]
hi @LuisCordobaDataSite,
thanks for reporting this issue. We'll work on a fix (display error details) for the next release. 
In the meantime you can use the `--debug` flag, which will display detailed information with the request and response from Atlas, including the error details:
`atlas logs download atlas-12uho2-shard-00-01.dssnf.mongodb.net mongodb-audit-log.gz --projectId 65a32c3fb244d862c601d12d --out /var/log/atlas/65a32c3fb244d862c601d12d_atlas-12uho2-shard-00-01.dssnf.mongodb.net_1712850826-1712852026-mongodb-audit-log.gz --start 1712850826 --end 1712852026 --debug`

**Comment by tibulca** [comment]
hi @LuisCordobaDataSite,
We have addressed this issue, and the `atlas logs download` command will now provide more detailed information about the cause of the error.
