### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by yonas** [mongodb/mongodb-atlas-cli#3135]
**Describe the bug**
Fails to build on FreeBSD.

**To Reproduce**
```sh
$ gmake build
fatal: No names found, cannot describe anything.
==> Building atlas binary
go build -ldflags "-s -w -X github.com/mongodb/mongodb-atlas-cli/atlascli/internal/version.GitCommit=9e2bbb075353290abd61086b9fcb38dbcf1ee6ba -X github.com/mongodb/mongodb-atlas-cli/atlascli/internal/version.Version=" -o ./bin/atlas ./cmd/atlas
# github.com/mongodb/mongodb-atlas-cli/atlascli/internal/compass
internal/compass/compass.go:29:9: undefined: binPath
internal/compass/compass.go:33:10: undefined: binPath
# github.com/mongodb/mongodb-atlas-cli/atlascli/internal/telemetry
internal/telemetry/tracker.go:67:21: undefined: readInstaller
gmake: *** [Makefile:118: build] Error 1
```

**Expected behavior**
Compile without error.

**Desktop (please complete the following information):**
 - OS: FreeBSD 14
 - MongoCLI version [9e2bbb0]

**Comment by gssbzn** [comment]
We don't officially support FreeBSD https://www.mongodb.com/docs/atlas/cli/current/compatibility/ if you want to submit a fix we are happy to review it but we make no promise we'll test or support FreeBSD in the future 

If you consider FreeBSD support is important you can submit a suggestion to https://feedback.mongodb.com/forums/930808-atlas-cli so we can evaluate it
