### ISSUE TITLE
(UnknownError) "userCommand.indexes[0].fields" is required when creating vector search index on local deployments

### ISSUE THREAD

**Issue by YoninL** [mongodb/mongodb-atlas-cli#3321]
**Describe the bug**
Command:
`atlas deployments search indexes create --deploymentName local9626  -f index.json`

index.json:
```json
{
  "collectionName": "test-collection",
  "database": "test",
  "definition": {
    "fields": [
      {
        "numDimensions": 1024,
        "path": "embedding",
        "similarity": "cosine",
        "type": "vector"
      }
    ]
  },
  "name": "vector_index",
  "type": "vectorSearch"
}
```

Output:
`Error: (UnknownError) "userCommand.indexes[0].fields" is required`
**To Reproduce**
1. Setup local dev env using the atlas cli
2. Run the command above to create the vector index
3. See error

**Expected behavior**
No errors, index can be created successfully.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 22.04.4
 - MongoCLI version
```
atlascli version: 1.29.0
git version: 04b1d057cff6f17ad13185c6a7f4fd0408473615
Go version: go1.22.7
   os: linux
   arch: amd64
   compiler: gc
```

**Comment by fmenezes** [comment]
Hello @YoninL thanks for reporting this issue, the issue has been reported to the relevant team.

**Comment by YoninL** [comment]
@fmenezes Thanks a lot for the fix. I tried the build from master branch and it works fine, when will you release the new version?
