### ISSUE TITLE
the granularity format used appears to be non-standard

### ISSUE THREAD

**Issue by SteveH-US** [mongodb/mongodb-atlas-cli#884]
**Describe the bug**
A clear and concise description of the bug.
It is not clear from the docs or from the CLI help output what granularity means for this command:
`mongocli atlas metrics processes sgh-test-shard-00-00.qurxw.mongodb.net:27017 --granularity 'P0Y0M0DT1H0M0S'`

One would assume that the ISO 8601 is in "ISO 8601 duration format". 

**To Reproduce**
1. Run `mongocli atlas metrics processes sgh-test-shard-00-00.qurxw.mongodb.net:27017 --granularity 'P0Y0M0DT1H0M0S'`
2. See error below:
```zsh
Error: GET https://cloud.mongodb.com/api/atlas/v1.0/groups/5fb434276f8323671cc1648c/processes/sgh-test-shard-00-00.qurxw.mongodb.net:27017/measurements?granularity=P3Y6M4DT12H30M5S: 400 (request "INVALID_GRANULARITY") An invalid granularity P3Y6M4DT12H30M5S was specified.
```

**Expected behavior**
Please explain what you expected to happen.
The code either should use the "ISO 8601 duration format" or be precise on what format is expected. AFAIK, if duration format is not used then the requested format is non-standard. 

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Mac oS
 - MongoCLI version 1.20.3
 - Ops Manager Version: Atlas

**Additional context**

**Comment by gssbzn** [comment]
> Since the standard itself is not available without paying for it, it would be helpful to have a reference that would explain the period syntax.

We are sadly limited on space and features given the type of interfaces available for a CLI, that said you can reference the linked PR to the changes I did to update the docs so any additional contribution is welcome to make them better 

I have also created an internal ticket to improve the validation of flags to cover your case on omitting `--period`
